/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountdownMask: typeof import('./src/components/countdownMask.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RewardMask: typeof import('./src/components/rewardMask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanFiled: typeof import('vant/es')['Filed']
    VanStepper: typeof import('vant/es')['Stepper']
  }
}
