# 基础镜像
FROM nginx
# author
MAINTAINER xht

# 挂载目录
VOLUME /home/xht/projects/xht-ui
# 创建目录
RUN mkdir -p /home/xht/projects/xht-ui
# 指定路径
WORKDIR /home/xht/projects/xht-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/xht/projects/xht-ui
